// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using akywedding_backend.Models.Database;

#nullable disable

namespace akywedding_backend.Migrations {
  [DbContext(typeof(WeddingContext))]
  partial class WeddingContextModelSnapshot : ModelSnapshot {
    protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.7")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("akywedding_backend.Models.Guest", b => {
        b.Property<long>("id")
            .ValueGeneratedOnAdd()
            .HasColumnType("bigint");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

        b.Property<bool>("isAttending")
            .HasColumnType("boolean");

        b.Property<string>("name")
            .IsRequired()
            .HasColumnType("text");

        b.HasKey("id");

        b.ToTable("guests");
      });

      modelBuilder.Entity("akywedding_backend.Models.Meal", b => {
        b.Property<long>("id")
            .ValueGeneratedOnAdd()
            .HasColumnType("bigint");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

        b.Property<long>("choiceid")
            .HasColumnType("bigint");

        b.Property<string>("dietaryRestrictions")
            .IsRequired()
            .HasColumnType("text");

        b.HasKey("id");

        b.HasIndex("choiceid");

        b.ToTable("meals");
      });

      modelBuilder.Entity("akywedding_backend.Models.MealOption", b => {
        b.Property<long>("id")
            .ValueGeneratedOnAdd()
            .HasColumnType("bigint");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

        b.Property<string>("name")
            .IsRequired()
            .HasColumnType("text");

        b.HasKey("id");

        b.ToTable("mealOptions");
      });

      modelBuilder.Entity("akywedding_backend.Models.Reception", b => {
        b.Property<long>("id")
            .ValueGeneratedOnAdd()
            .HasColumnType("bigint");

        NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

        b.Property<string>("comments")
            .IsRequired()
            .HasColumnType("text");

        b.Property<long>("guestid")
            .HasColumnType("bigint");

        b.Property<string>("music")
            .IsRequired()
            .HasColumnType("text");

        b.HasKey("id");

        b.HasIndex("guestid");

        b.ToTable("receptions");
      });

      modelBuilder.Entity("akywedding_backend.Models.Meal", b => {
        b.HasOne("akywedding_backend.Models.MealOption", "choice")
            .WithMany()
            .HasForeignKey("choiceid")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("choice");
      });

      modelBuilder.Entity("akywedding_backend.Models.Reception", b => {
        b.HasOne("akywedding_backend.Models.Guest", "guest")
            .WithMany()
            .HasForeignKey("guestid")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("guest");
      });
#pragma warning restore 612, 618
    }
  }
}
